{{- if include "opnc.renderBootstrapResources" . }}
{{ if .Values.gitlab.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-password
type: Opaque
data:
  password: {{ .Values.gitlab.initialRootPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-psql-password
type: Opaque
data:
  password: {{ .Values.gitlab.postgresql.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-password
type: Opaque
data:
  password: {{ .Values.gitlab.redis.password | b64enc }}
{{ end }}
{{- end }}
