{{- if .Values.environment }}
---
apiVersion: v1
kind: Secret
metadata:
  name: op-environment
data:
stringData:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
