opnc-integration:
  openprojectHost: "{{ pullpreview_public_dns }}"
  openprojectAssetHost: "openproject-assets.{{ pullpreview_public_dns }}"
  nextcloudHost: "nextcloud.{{ pullpreview_public_dns }}"
  keycloakHost: "keycloak.{{ pullpreview_public_dns }}"

openproject:
  enterpriseToken: |
    {{ requiredEnv "OPENPROJECT_ENTERPRISE_TOKEN" | nindent 4 }}
  openproject:
    host: "{{ pullpreview_public_dns }}"
    oidc:
      host: "keycloak.{{ pullpreview_public_dns }}"

  environment:
    OPENPROJECT_DEV_EXTRA_HOSTS: "{{ pullpreview_public_dns }}"
    OPENPROJECT_OPENID__CONNECT_KEYCLOAK_ISSUER: "https://keycloak.{{ pullpreview_public_dns }}/realms/opnc"
    OPENPROJECT_OPENID__CONNECT_KEYCLOAK_JWKS__URI: "https://keycloak.{{ pullpreview_public_dns }}/realms/opnc/protocol/openid-connect/certs"
    OPENPROJECT_OPENID__CONNECT_KEYCLOAK_POST__LOGOUT__REDIRECT__URI: "https://{{ pullpreview_public_dns }}/"

nextcloud:
  nextcloud:
    host: "nextcloud.{{ pullpreview_public_dns }}"
    extraEnv:
      - name: NC_GIT_SOURCE_BRANCH
        value: ""
      - name: OVERWRITEPROTOCOL
        value: https
      - name: OVERWRITECLIURL
        value: "https://nextcloud.{{ pullpreview_public_dns }}"
      - name: OIDC_KEYCLOAK_NEXTCLOUD_CLIENT_ID
        value: nextcloud
      - name: OIDC_KEYCLOAK_NEXTCLOUD_CLIENT_SECRET
        value: nextcloud-secret
      - name: OIDC_KEYCLOAK_PROVIDER_NAME
        value: keycloak
      - name: OIDC_KEYCLOAK_DISCOVERY_URL
        value: "https://keycloak.{{ pullpreview_public_dns }}/realms/opnc/.well-known/openid-configuration"
      - name: NEXTCLOUD_ENABLE_APPS
        valueFrom:
          configMapKeyRef:
            name: nextcloud-enable-apps
            key: enable-apps

keycloak:
  extraEnvVars:
    - name: KEYCLOAK_HOSTNAME
      value: "keycloak.{{ pullpreview_public_dns }}"
    - name: KC_REALM_NAME
      value: opnc
    - name: KC_NEXTCLOUD_CLIENT_ID
      value: nextcloud
    - name: KC_NEXTCLOUD_CLIENT_SECRET
      value: nextcloud-secret
    - name: KC_NEXTCLOUD_CLIENT_HOST
      value: "nextcloud.{{ pullpreview_public_dns }}"
    - name: KC_OPENPROJECT_CLIENT_ID
      value: openproject
    - name: KC_OPENPROJECT_CLIENT_SECRET
      value: openproject-secret
    - name: KC_OPENPROJECT_CLIENT_HOST
      value: "{{ pullpreview_public_dns }}"
