# {{ if .Values.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pg-password
  namespace: opnc-integration
type: Opaque
data:
  password: Z2l0bGFi

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-password
  namespace: opnc-integration
type: Opaque
data:
  password: Z1I4S21vVlhlN3dVbHA3VFM4bUdacklRMVN5N21lMFI=
{{ end }}

# kubectl -n opnc-integration create secret generic gitlab-gitlab-initial-root-password \
#   --from-literal=password=$(LC_CTYPE=C </dev/urandom tr -cd 'a-zA-Z0-9' | head -c 32)

# plain pass: Xi2WPMTNQHBFOD05CAPH3RpUj0Z5AInY